stages:
  - build
  - publish

variables:
  NODE_VERSION: "20"

.node_template:
  image: node:${NODE_VERSION}
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/

build:
  stage: build
  extends: .node_template
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run test
  rules:
    - if: $CI_COMMIT_TAG

publish:
  stage: publish
  extends: .node_template
  script:
    - npm ci --cache .npm --prefer-offline
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - npm publish
  rules:
    - if: $CI_COMMIT_TAG
