image: node:20

pipelines:
  tags:
    '*':
      - step:
          name: Build
          caches:
            - node
          script:
            - npm ci --cache .npm --prefer-offline
            - npm run test
      - step:
          name: Publish
          caches:
            - node
          script:
            - npm ci --cache .npm --prefer-offline
            - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
            - npm publish

definitions:
  caches:
    node: .npm/
