// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export enum DateRange {
  LAST_7_DAYS = 'last_7_days',
  LAST_30_DAYS = 'last_30_days',
  LAST_60_DAYS = 'last_60_days',
  LAST_90_DAYS = 'last_90_days',
  CUSTOM = 'custom',
}
