// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const replayRunDto = z.lazy(() => {
  return z.object({
    runId: z.string(),
  });
});

/**
 *
 * @typedef  {ReplayRunDto} replayRunDto
 * @property {string}
 */
export type ReplayRunDto = z.infer<typeof replayRunDto>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const replayRunDtoResponse = z.lazy(() => {
  return z
    .object({
      runId: z.string(),
    })
    .transform((data) => ({
      runId: data['runId'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const replayRunDtoRequest = z.lazy(() => {
  return z
    .object({
      runId: z.string(),
    })
    .transform((data) => ({
      runId: data['runId'],
    }));
});
