// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const sdkSendMessageDto = z.lazy(() => {
  return z.object({
    countryCode: z.string(),
    phoneNumber: z.string(),
    messageType: z.string(),
    templateName: z.string(),
    messageText: z.string(),
    components: z.array(z.string()),
    context: z.any(),
    mediaMessage: z.any().optional(),
    media: z.any().optional(),
  });
});

/**
 *
 * @typedef  {SdkSendMessageDto} sdkSendMessageDto
 * @property {string}
 * @property {string}
 * @property {string}
 * @property {string}
 * @property {string}
 * @property {string[]}
 * @property {any}
 * @property {any}
 * @property {any}
 */
export type SdkSendMessageDto = z.infer<typeof sdkSendMessageDto>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const sdkSendMessageDtoResponse = z.lazy(() => {
  return z
    .object({
      country_code: z.string(),
      phone_number: z.string(),
      messageType: z.string(),
      template_name: z.string(),
      messageText: z.string(),
      components: z.array(z.string()),
      context: z.any(),
      mediaMessage: z.any().optional(),
      media: z.any().optional(),
    })
    .transform((data) => ({
      countryCode: data['country_code'],
      phoneNumber: data['phone_number'],
      messageType: data['messageType'],
      templateName: data['template_name'],
      messageText: data['messageText'],
      components: data['components'],
      context: data['context'],
      mediaMessage: data['mediaMessage'],
      media: data['media'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const sdkSendMessageDtoRequest = z.lazy(() => {
  return z
    .object({
      countryCode: z.string(),
      phoneNumber: z.string(),
      messageType: z.string(),
      templateName: z.string(),
      messageText: z.string(),
      components: z.array(z.string()),
      context: z.any(),
      mediaMessage: z.any().optional(),
      media: z.any().optional(),
    })
    .transform((data) => ({
      country_code: data['countryCode'],
      phone_number: data['phoneNumber'],
      messageType: data['messageType'],
      template_name: data['templateName'],
      messageText: data['messageText'],
      components: data['components'],
      context: data['context'],
      mediaMessage: data['mediaMessage'],
      media: data['media'],
    }));
});
