// This file was generated by liblab | https://liblab.com/

import { SendMessageDto, TriochatSdk } from '@triochat/triochat-sdk';

(async () => {
  const triochatSdk = new TriochatSdk({});

  const sendMessageDto: SendMessageDto = {
    countryCode: 'country_code',
    phoneNumber: 'phone_number',
    messageType: 'messageType',
    templateName: 'template_name',
    leadId: {},
    chatId: {},
    messageText: 'messageText',
    components: ['components'],
    context: {},
    mediaMessage: {},
    userId: {},
    media: {},
  };

  const { data } = await triochatSdk.api.sendMessageControllerSendMessage(sendMessageDto);

  console.log(data);
})();
