// This file was generated by liblab | https://liblab.com/

import { SdkSendMessageDto, TriochatSdk } from '@triochat/triochat-sdk';

(async () => {
  const triochatSdk = new TriochatSdk({});

  const sdkSendMessageDto: SdkSendMessageDto = {
    countryCode: 'country_code',
    phoneNumber: 'phone_number',
    messageType: 'messageType',
    templateName: 'template_name',
    messageText: 'messageText',
    components: [{}],
    context: {},
    mediaMessage: {},
    media: {},
  };

  const { data } = await triochatSdk.sdk.sdkControllerSendMessage(sdkSendMessageDto);

  console.log(data);
})();
