// This file was generated by liblab | https://liblab.com/

import { TriochatSdk } from '@triochat/@triochat/triochat-sdk';

(async () => {
  const triochatSdk = new TriochatSdk({});

  const { data } = await triochatSdk.internal.internalControllerCreateAccessToken();

  console.log(data);
})();
