// This file was generated by liblab | https://liblab.com/

import { Status } from './models/status';
import { DateRange } from './models/date-range';

export interface SchedulingControllerRescheduleRunParams {
  runId: string;
  newDelay: string;
}

export interface SchedulingControllerListRunsParams {
  userId: string;
  page?: number;
  pageSize?: number;
  status?: Status[];
  dateRange?: DateRange;
  searchQuery?: string;
  customDateRange?: any;
}

export interface SchedulingControllerCancelRunParams {
  runId: string;
}

export interface SchedulingControllerRetryRunParams {
  runId: string;
}
