// This file was generated by liblab | https://liblab.com/

import { Environment } from './http/environment';
import { SdkConfig } from './http/types';
import { SchedulingService } from './services/scheduling';
import { InternalService } from './services/internal';
import { CampaignService } from './services/campaign';

export * from './services/scheduling';
export * from './services/internal';
export * from './services/campaign';

export * from './http';
export { Environment } from './http/environment';

export class TriochatSdk {
  public readonly scheduling: SchedulingService;

  public readonly internal: InternalService;

  public readonly campaign: CampaignService;

  constructor(public config: SdkConfig) {
    this.scheduling = new SchedulingService(this.config);

    this.internal = new InternalService(this.config);

    this.campaign = new CampaignService(this.config);
  }

  set baseUrl(baseUrl: string) {
    this.scheduling.baseUrl = baseUrl;
    this.internal.baseUrl = baseUrl;
    this.campaign.baseUrl = baseUrl;
  }

  set environment(environment: Environment) {
    this.scheduling.baseUrl = environment;
    this.internal.baseUrl = environment;
    this.campaign.baseUrl = environment;
  }

  set timeoutMs(timeoutMs: number) {
    this.scheduling.timeoutMs = timeoutMs;
    this.internal.timeoutMs = timeoutMs;
    this.campaign.timeoutMs = timeoutMs;
  }
}

// c029837e0e474b76bc487506e8799df5e3335891efe4fb02bda7a1441840310c
