// This file was generated by liblab | https://liblab.com/

import { Environment } from './http/environment';
import { SdkConfig } from './http/types';
import { ApiService } from './services/api';

export * from './services/api';

export * from './http';
export { Environment } from './http/environment';

export class TriochatSdk {
  public readonly api: ApiService;

  constructor(public config: SdkConfig) {
    this.api = new ApiService(this.config);
  }

  set baseUrl(baseUrl: string) {
    this.api.baseUrl = baseUrl;
  }

  set environment(environment: Environment) {
    this.api.baseUrl = environment;
  }

  set timeoutMs(timeoutMs: number) {
    this.api.timeoutMs = timeoutMs;
  }
}

// c029837e0e474b76bc487506e8799df5e3335891efe4fb02bda7a1441840310c
