// This file was generated by liblab | https://liblab.com/

import { Environment } from './http/environment';
import { SdkConfig } from './http/types';
import { SdkService } from './services/sdk';

export * from './services/sdk';

export * from './http';
export { Environment } from './http/environment';

export class TriochatSdk {
  public readonly sdk: SdkService;

  constructor(public config: SdkConfig) {
    this.sdk = new SdkService(this.config);
  }

  set baseUrl(baseUrl: string) {
    this.sdk.baseUrl = baseUrl;
  }

  set environment(environment: Environment) {
    this.sdk.baseUrl = environment;
  }

  set timeoutMs(timeoutMs: number) {
    this.sdk.timeoutMs = timeoutMs;
  }

  set token(token: string) {
    this.sdk.token = token;
  }
}

// c029837e0e474b76bc487506e8799df5e3335891efe4fb02bda7a1441840310c
